### ISSUE TITLE
USER STORY 1

### ISSUE THREAD

**Issue by wictorsson** [wictorsson/modular-spiced#1]
## Value proposition

As a user:
I want to generate sound by adding and connecting graphical components/modules to each other. 
So that:
I can build my own software instruments and create music or noise in a playful environment. 

## Description

Drag and connect react flow GUI modules with each other. Each module node connection executes a block of audio-related code.
 

![Image](https://user-images.githubusercontent.com/27869958/232739482-9270f17d-f0e3-45bb-923b-763d5beba881.png)

## Acceptance criteria

- [ ] Modules should be draggable. 
- [ ] If module is connected to audio-out module, there should be sound
- [ ] If module is NOT connected to audio-out module, there should be NO sound generated from that module

## Tasks
- [ ] Project setup, Next.js
- [ ] Implement Tone.js to be able to play and process audio. 
- [ ] Implement React flow for the module GUI. 
- [ ] Implement trigger between module and audio out.
