### ISSUE TITLE
User story 5

### ISSUE THREAD

**Issue by wictorsson** [wictorsson/modular-spiced#10]
## Value proposition

As a user:
I want to log in to a private user account so I can store my own patches or publish them if I want.

## Description

Set up login with google, email and github. User can login and save, load and delete patches. The user can choose to keep the patch private or publish it to a public list. 

![Image](https://user-images.githubusercontent.com/27869958/236149784-b87d521c-9871-4a2e-a8f0-770341361241.png)

## Acceptance criteria

- [x] User should be able to login
- [x] User should be able to save, load, delete and publish their patches. 
 

## Tasks
- [x] Implement login
- [x] Implement flags and id checks in the database scheme
