### ISSUE TITLE
USER STORY 2

### ISSUE THREAD

**Issue by wictorsson** [wictorsson/modular-spiced#2]
## Value proposition

As a user:
I want to connect new modules between my source and the audio output to alternate the sound.  
So that:
I can make processing and variations of the sound. 

## Description

Add new module and drag virtual cables between source->processing module->output. 

![Image](https://user-images.githubusercontent.com/27869958/232786874-7de0aa7d-cafd-40bd-a2e5-111dda14085f.png)

## Acceptance criteria

- [ ] There should only be sound if all cables are connected
- [ ] The new module should do something to the sound. 
- [ ] There should be a way (parameter) to change the sound from the new module. 

## Tasks
- [ ] Add new module(s). This module should have a processing function, (GAIN, EQ, REVERB...) check Tone.js
- [ ] Implement a way of detecting what kind of module is connect (what node in React flow) and perform processing according to that information.
