### ISSUE TITLE
USER STORY 3

### ISSUE THREAD

**Issue by wictorsson** [wictorsson/modular-spiced#3]
## Value proposition

As a user:
I want to be able to add and delete modules. 
So that:
I can make more sounds and variations.  

## Description

Add module from the sidebar. Drag and connect GUI modules to the output. Each module node connection executes a block of audio-related code. 

![Image](https://user-images.githubusercontent.com/27869958/232800546-cfacb7df-8e56-4b8a-adc6-65e1374b7527.png)

## Acceptance criteria

- [ ] User should be able to add and delete audio module. 
- [ ] Each type of audio module should have their own function. (Different sound or processing function). 

## Tasks
- [ ] Add sidebar with a view of available components
- [ ] Implement add buttons or - nice to have - drag and drop function.
- [ ] Implement delete cross (X) on the modules. Implement the function to delete when clicked.
