### ISSUE TITLE
User Story 4

### ISSUE THREAD

**Issue by wictorsson** [wictorsson/modular-spiced#8]
## Value proposition

As a user:
I want to save and load modules and connections (patch) from a database

## Description

Add module from the sidebar. Drag and connect GUI modules to the output. Each module node connection executes a block of audio-related code. Save the patch (modules and connections)into a database. Load a patch from the database. Modules and connections are stored in two arrays containing objects.  

![Image](https://user-images.githubusercontent.com/27869958/235345706-c175b421-28c9-46c5-b4f8-036ab977b9f2.png)

![Image](https://user-images.githubusercontent.com/27869958/235447830-dcf623d4-bc70-47b3-a46c-16852e852033.png)

## Acceptance criteria

- [ ] User should be able to save and load a patch 
 

## Tasks
- [ ] Implement save button
- [ ] Implement list of saved patches that can be loaded
- [ ] Implement database.
